# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ride_type',
            field=models.CharField(choices=[(b'cng', b'cng'), (b'uber', b'uber')], default=b'cng', max_length=20),
        ),
    ]
